spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    org.springframework.jdbc.datasource: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
server:
  port: 3003