server:
  port: 3000

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:3001
          predicates:
            - Path=/user/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 5
              burstCapacity: 10
  data:
    redis:
        host: localhost
        port: 6379
  level:
    org.springframework.jdbc.datasource: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
    gateway:
      enabled: true
  endpoint:
    gateway:
      enabled: true